# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/scholaris-minimal-reproduction-1',
                'doc_host': 'https://nicomarr.github.io',
                'git_url': 'https://github.com/nicomarr/scholaris-minimal-reproduction-1',
                'lib_path': 'scholaris_minimal_reproduction_1'},
  'syms': { 'scholaris_minimal_reproduction_1.core': { 'scholaris_minimal_reproduction_1.core.foo': ( 'core.html#foo',
                                                                                                      'scholaris_minimal_reproduction_1/core.py')}}}
